const CDN_PATH="https://cdn.jsdelivr.net/gh/joethun/EmulatorJS-With-Cores/";window.gameRunning=false;const FILE_EXTENSIONS={fds:"nes",nes:"nes",unif:"nes",unf:"nes",gb:"gb",gbc:"gbc",gba:"gba",smc:"snes",sfc:"snes",swc:"snes",vb:"vb",vboy:"vb",z64:"n64",n64:"n64",nds:"nds",sms:"segaMS",md:"segaMD",gen:"segaMD",smd:"segaMD",gg:"segaGG","32x":"sega32x",cso:"psp",pbp:"psp",a26:"atari2600",a52:"atari5200",a78:"atari7800",lnx:"lynx",j64:"jaguar",jag:"jaguar",d64:"vice_x64",t64:"vice_x64",tap:"vice_x64",crt:"vice_x64",col:"coleco",cv:"coleco",pce:"pce",ngp:"ngp",ngc:"ngp",ws:"ws",wsc:"ws"};const SYSTEM_PICKER={"Nintendo NES":"nes","Nintendo GB":"gb","Nintendo SNES":"snes","Nintendo VB":"vb","Nintendo 64":"n64","Nintendo GBC":"gbc","Nintendo GBA":"gba","Nintendo DS":"nds","Sega MS":"segaMS","Sega Gen/MD":"segaMD","Sega GG":"segaGG","Sega CD":"segaCD","Sega 32X":"sega32x","Sega Saturn":"segaSaturn","Sony PS1":"psx","Sony PSP":"psp","Atari 2600":"atari2600","Atari 5200":"atari5200","Atari 7800":"atari7800","Atari Lynx":"lynx","Atari Jaguar":"jaguar","Panasonic 3DO":"opera","Arcade (FBNeo)":"arcade","Arcade (M.A.M.E)":"mame2003_plus","Microsoft DOS":"dosbox_pure","Commodore PET":"vice_xpet","Commodore VIC20":"vice_xvic","Commodore Amiga":"amiga","Commodore 64":"vice_x64","Commodore 128":"vice_x128","Commodore P/4":"vice_xplus4","ColecoVision":"coleco","NEC TurboGrafx-16":"pce","NEC PC-FX":"pcfx","SNK NGP":"ngp","Bandai WS":"ws"};async function detectCore(extension){if(FILE_EXTENSIONS[extension]){return FILE_EXTENSIONS[extension];}
return new Promise((resolve)=>{window.showSystemPicker(SYSTEM_PICKER,resolve);});}
async function loadGame(file){const fileName=file.name;const fileExtension=fileName.split(".").pop().toLowerCase();const gameName=fileName.substring(0,fileName.lastIndexOf("."));const core=await detectCore(fileExtension);window.cleanupOldElements();window.hideMenu();window.createGameDisplay();window.gameRunning=true;configureEmulator(gameName,file,core);loadEmulatorScript();}
function configureEmulator(gameName,gameFile,core){window.EJS_color="#003d8c";window.EJS_backgroundColor="#000000";window.EJS_player="#game";window.EJS_gameName=gameName;window.EJS_gameUrl=gameFile;window.EJS_core=core;window.EJS_pathtodata=CDN_PATH;window.EJS_startOnLoaded=true;window.EJS_biosUrl="";const threadsEnabled=["psp","dosbox_pure"];if(threadsEnabled.includes(core)){window.EJS_threads=true;}
window.EJS_defaultOptions={"save-save-interval":"60","desmume_advanced_timing":"disabled","webgl2Enabled":"enabled",...(core==="segaGG"&&{retroarch_core:"genesis_plus_gx"}),...(core==="nds"&&{retroarch_core:"desmume"})};window.EJS_Buttons={exitEmulation:false,cacheManager:false,saveSavFiles:{visible:false},loadSavFiles:{visible:false}};}
function loadEmulatorScript(){const script=document.createElement("script");script.src=`${CDN_PATH}/loader.js`;document.body.appendChild(script);}
async function saveState(){const emulator=window.EJS_emulator;if(!emulator?.started){return;}
try{const state=emulator.gameManager.getState();const stateFileName=`${emulator.getBaseFileName()}.state`;await emulator.storage.states.put(stateFileName,state);emulator.displayMessage("SAVED STATE TO BROWSER");}catch(error){console.error("Save failed:",error);emulator.displayMessage(`Error saving: ${error.message}`);}}
async function loadState(){const emulator=window.EJS_emulator;if(!emulator?.started){return;}
try{const stateFileName=`${emulator.getBaseFileName()}.state`;const state=await emulator.storage.states.get(stateFileName);if(state){await emulator.gameManager.loadState(state);emulator.displayMessage("LOADED STATE FROM BROWSER");}else{emulator.displayMessage("");}}catch(error){console.error("Load failed:",error);emulator.displayMessage(`Error loading: ${error.message}`);}}
function addEventListeners(){document.addEventListener("keydown",(event)=>{if(event.key==="F1"){event.preventDefault();saveState();}else if(event.key==="F2"){event.preventDefault();loadState();}});const saveButton=document.getElementById("saveBrowser");const loadButton=document.getElementById("loadBrowser");if(saveButton){saveButton.onclick=saveState;}
if(loadButton){loadButton.onclick=loadState;}}
window.saveToBrowserStorage=saveState;window.loadFromBrowserStorage=loadState;window.loadGame=loadGame;document.addEventListener("DOMContentLoaded",addEventListeners);